// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface DataProductUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataProductUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UserInfo user_info = 1;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.UserInfo user_info = 1;</code>
   * @return The userInfo.
   */
  org.apache.airavata.datacatalog.api.UserInfo getUserInfo();
  /**
   * <code>.UserInfo user_info = 1;</code>
   */
  org.apache.airavata.datacatalog.api.UserInfoOrBuilder getUserInfoOrBuilder();

  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return Whether the dataProduct field is set.
   */
  boolean hasDataProduct();
  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return The dataProduct.
   */
  org.apache.airavata.datacatalog.api.DataProduct getDataProduct();
  /**
   * <code>.DataProduct data_product = 2;</code>
   */
  org.apache.airavata.datacatalog.api.DataProductOrBuilder getDataProductOrBuilder();
}
