// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface DataProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data_product_id = 1;</code>
   * @return The dataProductId.
   */
  java.lang.String getDataProductId();
  /**
   * <code>string data_product_id = 1;</code>
   * @return The bytes for dataProductId.
   */
  com.google.protobuf.ByteString
      getDataProductIdBytes();

  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return Whether the parentDataProductId field is set.
   */
  boolean hasParentDataProductId();
  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return The parentDataProductId.
   */
  java.lang.String getParentDataProductId();
  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return The bytes for parentDataProductId.
   */
  com.google.protobuf.ByteString
      getParentDataProductIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional string metadata = 4;</code>
   * @return The metadata.
   */
  java.lang.String getMetadata();
  /**
   * <code>optional string metadata = 4;</code>
   * @return The bytes for metadata.
   */
  com.google.protobuf.ByteString
      getMetadataBytes();

  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @return A list containing the metadataSchemas.
   */
  java.util.List<java.lang.String>
      getMetadataSchemasList();
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @return The count of metadataSchemas.
   */
  int getMetadataSchemasCount();
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @param index The index of the element to return.
   * @return The metadataSchemas at the given index.
   */
  java.lang.String getMetadataSchemas(int index);
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the metadataSchemas at the given index.
   */
  com.google.protobuf.ByteString
      getMetadataSchemasBytes(int index);

  /**
   * <code>.UserInfo owner = 6;</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <code>.UserInfo owner = 6;</code>
   * @return The owner.
   */
  org.apache.airavata.datacatalog.api.UserInfo getOwner();
  /**
   * <code>.UserInfo owner = 6;</code>
   */
  org.apache.airavata.datacatalog.api.UserInfoOrBuilder getOwnerOrBuilder();
}
