// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface DataProductCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataProductCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DataProduct data_product = 1;</code>
   * @return Whether the dataProduct field is set.
   */
  boolean hasDataProduct();
  /**
   * <code>.DataProduct data_product = 1;</code>
   * @return The dataProduct.
   */
  org.apache.airavata.datacatalog.api.DataProduct getDataProduct();
  /**
   * <code>.DataProduct data_product = 1;</code>
   */
  org.apache.airavata.datacatalog.api.DataProductOrBuilder getDataProductOrBuilder();
}
