// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

/**
 * Protobuf type {@code DataProduct}
 */
public final class DataProduct extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:DataProduct)
    DataProductOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      DataProduct.class.getName());
  }
  // Use DataProduct.newBuilder() to construct.
  private DataProduct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DataProduct() {
    dataProductId_ = "";
    parentDataProductId_ = "";
    name_ = "";
    metadata_ = "";
    metadataSchemas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_DataProduct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_DataProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.airavata.datacatalog.api.DataProduct.class, org.apache.airavata.datacatalog.api.DataProduct.Builder.class);
  }

  private int bitField0_;
  public static final int DATA_PRODUCT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataProductId_ = "";
  /**
   * <code>string data_product_id = 1;</code>
   * @return The dataProductId.
   */
  @java.lang.Override
  public java.lang.String getDataProductId() {
    java.lang.Object ref = dataProductId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataProductId_ = s;
      return s;
    }
  }
  /**
   * <code>string data_product_id = 1;</code>
   * @return The bytes for dataProductId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataProductIdBytes() {
    java.lang.Object ref = dataProductId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataProductId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_DATA_PRODUCT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentDataProductId_ = "";
  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return Whether the parentDataProductId field is set.
   */
  @java.lang.Override
  public boolean hasParentDataProductId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return The parentDataProductId.
   */
  @java.lang.Override
  public java.lang.String getParentDataProductId() {
    java.lang.Object ref = parentDataProductId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentDataProductId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string parent_data_product_id = 2;</code>
   * @return The bytes for parentDataProductId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentDataProductIdBytes() {
    java.lang.Object ref = parentDataProductId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentDataProductId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object metadata_ = "";
  /**
   * <code>optional string metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string metadata = 4;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public java.lang.String getMetadata() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metadata_ = s;
      return s;
    }
  }
  /**
   * <code>optional string metadata = 4;</code>
   * @return The bytes for metadata.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataBytes() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadata_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_SCHEMAS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList metadataSchemas_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @return A list containing the metadataSchemas.
   */
  public com.google.protobuf.ProtocolStringList
      getMetadataSchemasList() {
    return metadataSchemas_;
  }
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @return The count of metadataSchemas.
   */
  public int getMetadataSchemasCount() {
    return metadataSchemas_.size();
  }
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @param index The index of the element to return.
   * @return The metadataSchemas at the given index.
   */
  public java.lang.String getMetadataSchemas(int index) {
    return metadataSchemas_.get(index);
  }
  /**
   * <code>repeated string metadata_schemas = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the metadataSchemas at the given index.
   */
  public com.google.protobuf.ByteString
      getMetadataSchemasBytes(int index) {
    return metadataSchemas_.getByteString(index);
  }

  public static final int OWNER_FIELD_NUMBER = 6;
  private org.apache.airavata.datacatalog.api.UserInfo owner_;
  /**
   * <code>.UserInfo owner = 6;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.UserInfo owner = 6;</code>
   * @return The owner.
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.UserInfo getOwner() {
    return owner_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : owner_;
  }
  /**
   * <code>.UserInfo owner = 6;</code>
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.UserInfoOrBuilder getOwnerOrBuilder() {
    return owner_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : owner_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataProductId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, dataProductId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, parentDataProductId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, metadata_);
    }
    for (int i = 0; i < metadataSchemas_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, metadataSchemas_.getRaw(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getOwner());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataProductId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, dataProductId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, parentDataProductId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, metadata_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < metadataSchemas_.size(); i++) {
        dataSize += computeStringSizeNoTag(metadataSchemas_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMetadataSchemasList().size();
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getOwner());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.airavata.datacatalog.api.DataProduct)) {
      return super.equals(obj);
    }
    org.apache.airavata.datacatalog.api.DataProduct other = (org.apache.airavata.datacatalog.api.DataProduct) obj;

    if (!getDataProductId()
        .equals(other.getDataProductId())) return false;
    if (hasParentDataProductId() != other.hasParentDataProductId()) return false;
    if (hasParentDataProductId()) {
      if (!getParentDataProductId()
          .equals(other.getParentDataProductId())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getMetadataSchemasList()
        .equals(other.getMetadataSchemasList())) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDataProductId().hashCode();
    if (hasParentDataProductId()) {
      hash = (37 * hash) + PARENT_DATA_PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getParentDataProductId().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (getMetadataSchemasCount() > 0) {
      hash = (37 * hash) + METADATA_SCHEMAS_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataSchemasList().hashCode();
    }
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.airavata.datacatalog.api.DataProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.airavata.datacatalog.api.DataProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.DataProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.airavata.datacatalog.api.DataProduct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DataProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DataProduct)
      org.apache.airavata.datacatalog.api.DataProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_DataProduct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_DataProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.airavata.datacatalog.api.DataProduct.class, org.apache.airavata.datacatalog.api.DataProduct.Builder.class);
    }

    // Construct using org.apache.airavata.datacatalog.api.DataProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getOwnerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dataProductId_ = "";
      parentDataProductId_ = "";
      name_ = "";
      metadata_ = "";
      metadataSchemas_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_DataProduct_descriptor;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.DataProduct getDefaultInstanceForType() {
      return org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.DataProduct build() {
      org.apache.airavata.datacatalog.api.DataProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.DataProduct buildPartial() {
      org.apache.airavata.datacatalog.api.DataProduct result = new org.apache.airavata.datacatalog.api.DataProduct(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.airavata.datacatalog.api.DataProduct result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dataProductId_ = dataProductId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.parentDataProductId_ = parentDataProductId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.metadata_ = metadata_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        metadataSchemas_.makeImmutable();
        result.metadataSchemas_ = metadataSchemas_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.owner_ = ownerBuilder_ == null
            ? owner_
            : ownerBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.airavata.datacatalog.api.DataProduct) {
        return mergeFrom((org.apache.airavata.datacatalog.api.DataProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.airavata.datacatalog.api.DataProduct other) {
      if (other == org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance()) return this;
      if (!other.getDataProductId().isEmpty()) {
        dataProductId_ = other.dataProductId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasParentDataProductId()) {
        parentDataProductId_ = other.parentDataProductId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasMetadata()) {
        metadata_ = other.metadata_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.metadataSchemas_.isEmpty()) {
        if (metadataSchemas_.isEmpty()) {
          metadataSchemas_ = other.metadataSchemas_;
          bitField0_ |= 0x00000010;
        } else {
          ensureMetadataSchemasIsMutable();
          metadataSchemas_.addAll(other.metadataSchemas_);
        }
        onChanged();
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dataProductId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              parentDataProductId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              metadata_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureMetadataSchemasIsMutable();
              metadataSchemas_.add(s);
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getOwnerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dataProductId_ = "";
    /**
     * <code>string data_product_id = 1;</code>
     * @return The dataProductId.
     */
    public java.lang.String getDataProductId() {
      java.lang.Object ref = dataProductId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataProductId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data_product_id = 1;</code>
     * @return The bytes for dataProductId.
     */
    public com.google.protobuf.ByteString
        getDataProductIdBytes() {
      java.lang.Object ref = dataProductId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataProductId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data_product_id = 1;</code>
     * @param value The dataProductId to set.
     * @return This builder for chaining.
     */
    public Builder setDataProductId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataProductId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string data_product_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataProductId() {
      dataProductId_ = getDefaultInstance().getDataProductId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string data_product_id = 1;</code>
     * @param value The bytes for dataProductId to set.
     * @return This builder for chaining.
     */
    public Builder setDataProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataProductId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object parentDataProductId_ = "";
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @return Whether the parentDataProductId field is set.
     */
    public boolean hasParentDataProductId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @return The parentDataProductId.
     */
    public java.lang.String getParentDataProductId() {
      java.lang.Object ref = parentDataProductId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentDataProductId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @return The bytes for parentDataProductId.
     */
    public com.google.protobuf.ByteString
        getParentDataProductIdBytes() {
      java.lang.Object ref = parentDataProductId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentDataProductId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @param value The parentDataProductId to set.
     * @return This builder for chaining.
     */
    public Builder setParentDataProductId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentDataProductId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentDataProductId() {
      parentDataProductId_ = getDefaultInstance().getParentDataProductId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string parent_data_product_id = 2;</code>
     * @param value The bytes for parentDataProductId to set.
     * @return This builder for chaining.
     */
    public Builder setParentDataProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentDataProductId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object metadata_ = "";
    /**
     * <code>optional string metadata = 4;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string metadata = 4;</code>
     * @return The metadata.
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string metadata = 4;</code>
     * @return The bytes for metadata.
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string metadata = 4;</code>
     * @param value The metadata to set.
     * @return This builder for chaining.
     */
    public Builder setMetadata(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      metadata_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadata = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadata() {
      metadata_ = getDefaultInstance().getMetadata();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string metadata = 4;</code>
     * @param value The bytes for metadata to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      metadata_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList metadataSchemas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMetadataSchemasIsMutable() {
      if (!metadataSchemas_.isModifiable()) {
        metadataSchemas_ = new com.google.protobuf.LazyStringArrayList(metadataSchemas_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @return A list containing the metadataSchemas.
     */
    public com.google.protobuf.ProtocolStringList
        getMetadataSchemasList() {
      metadataSchemas_.makeImmutable();
      return metadataSchemas_;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @return The count of metadataSchemas.
     */
    public int getMetadataSchemasCount() {
      return metadataSchemas_.size();
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param index The index of the element to return.
     * @return The metadataSchemas at the given index.
     */
    public java.lang.String getMetadataSchemas(int index) {
      return metadataSchemas_.get(index);
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the metadataSchemas at the given index.
     */
    public com.google.protobuf.ByteString
        getMetadataSchemasBytes(int index) {
      return metadataSchemas_.getByteString(index);
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param index The index to set the value at.
     * @param value The metadataSchemas to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataSchemas(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMetadataSchemasIsMutable();
      metadataSchemas_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param value The metadataSchemas to add.
     * @return This builder for chaining.
     */
    public Builder addMetadataSchemas(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMetadataSchemasIsMutable();
      metadataSchemas_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param values The metadataSchemas to add.
     * @return This builder for chaining.
     */
    public Builder addAllMetadataSchemas(
        java.lang.Iterable<java.lang.String> values) {
      ensureMetadataSchemasIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, metadataSchemas_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadataSchemas() {
      metadataSchemas_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metadata_schemas = 5;</code>
     * @param value The bytes of the metadataSchemas to add.
     * @return This builder for chaining.
     */
    public Builder addMetadataSchemasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMetadataSchemasIsMutable();
      metadataSchemas_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private org.apache.airavata.datacatalog.api.UserInfo owner_;
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder> ownerBuilder_;
    /**
     * <code>.UserInfo owner = 6;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     * @return The owner.
     */
    public org.apache.airavata.datacatalog.api.UserInfo getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public Builder setOwner(org.apache.airavata.datacatalog.api.UserInfo value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
      } else {
        ownerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public Builder setOwner(
        org.apache.airavata.datacatalog.api.UserInfo.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public Builder mergeOwner(org.apache.airavata.datacatalog.api.UserInfo value) {
      if (ownerBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          owner_ != null &&
          owner_ != org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance()) {
          getOwnerBuilder().mergeFrom(value);
        } else {
          owner_ = value;
        }
      } else {
        ownerBuilder_.mergeFrom(value);
      }
      if (owner_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public Builder clearOwner() {
      bitField0_ = (bitField0_ & ~0x00000020);
      owner_ = null;
      if (ownerBuilder_ != null) {
        ownerBuilder_.dispose();
        ownerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public org.apache.airavata.datacatalog.api.UserInfo.Builder getOwnerBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    public org.apache.airavata.datacatalog.api.UserInfoOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.UserInfo owner = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:DataProduct)
  }

  // @@protoc_insertion_point(class_scope:DataProduct)
  private static final org.apache.airavata.datacatalog.api.DataProduct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.airavata.datacatalog.api.DataProduct();
  }

  public static org.apache.airavata.datacatalog.api.DataProduct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataProduct>
      PARSER = new com.google.protobuf.AbstractParser<DataProduct>() {
    @java.lang.Override
    public DataProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataProduct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataProduct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.airavata.datacatalog.api.DataProduct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

