// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface GroupInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *
   * This is an external identifier for the group, which identifies the group in
   * whatever group management scheme data catalog is integrated with.
   * </pre>
   *
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <pre>
   *
   * This is an external identifier for the group, which identifies the group in
   * whatever group management scheme data catalog is integrated with.
   * </pre>
   *
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <pre>
   *
   * This is an (optional) external identifier for the tenant, which
   * identifies the tenant in whatever tenant management scheme data catalog
   * is integrated with.
   * </pre>
   *
   * <code>optional string tenant_id = 2;</code>
   * @return Whether the tenantId field is set.
   */
  boolean hasTenantId();
  /**
   * <pre>
   *
   * This is an (optional) external identifier for the tenant, which
   * identifies the tenant in whatever tenant management scheme data catalog
   * is integrated with.
   * </pre>
   *
   * <code>optional string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   *
   * This is an (optional) external identifier for the tenant, which
   * identifies the tenant in whatever tenant management scheme data catalog
   * is integrated with.
   * </pre>
   *
   * <code>optional string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
