// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface MetadataSchemaCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetadataSchemaCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MetadataSchema metadata_schema = 1;</code>
   * @return Whether the metadataSchema field is set.
   */
  boolean hasMetadataSchema();
  /**
   * <code>.MetadataSchema metadata_schema = 1;</code>
   * @return The metadataSchema.
   */
  org.apache.airavata.datacatalog.api.MetadataSchema getMetadataSchema();
  /**
   * <code>.MetadataSchema metadata_schema = 1;</code>
   */
  org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder getMetadataSchemaOrBuilder();
}
