// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface MetadataSchemaDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetadataSchemaDeleteResponse)
    com.google.protobuf.MessageOrBuilder {
}
