// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface MetadataSchemaFieldListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetadataSchemaFieldListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MetadataSchemaField metadata_schema_fields = 1;</code>
   */
  java.util.List<org.apache.airavata.datacatalog.api.MetadataSchemaField> 
      getMetadataSchemaFieldsList();
  /**
   * <code>repeated .MetadataSchemaField metadata_schema_fields = 1;</code>
   */
  org.apache.airavata.datacatalog.api.MetadataSchemaField getMetadataSchemaFields(int index);
  /**
   * <code>repeated .MetadataSchemaField metadata_schema_fields = 1;</code>
   */
  int getMetadataSchemaFieldsCount();
  /**
   * <code>repeated .MetadataSchemaField metadata_schema_fields = 1;</code>
   */
  java.util.List<? extends org.apache.airavata.datacatalog.api.MetadataSchemaFieldOrBuilder> 
      getMetadataSchemaFieldsOrBuilderList();
  /**
   * <code>repeated .MetadataSchemaField metadata_schema_fields = 1;</code>
   */
  org.apache.airavata.datacatalog.api.MetadataSchemaFieldOrBuilder getMetadataSchemaFieldsOrBuilder(
      int index);
}
