// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface MetadataSchemaFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetadataSchemaField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string schema_name = 1;</code>
   * @return The schemaName.
   */
  java.lang.String getSchemaName();
  /**
   * <code>string schema_name = 1;</code>
   * @return The bytes for schemaName.
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <code>string field_name = 2;</code>
   * @return The fieldName.
   */
  java.lang.String getFieldName();
  /**
   * <code>string field_name = 2;</code>
   * @return The bytes for fieldName.
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <code>string json_path = 3;</code>
   * @return The jsonPath.
   */
  java.lang.String getJsonPath();
  /**
   * <code>string json_path = 3;</code>
   * @return The bytes for jsonPath.
   */
  com.google.protobuf.ByteString
      getJsonPathBytes();

  /**
   * <code>.FieldValueType value_type = 4;</code>
   * @return The enum numeric value on the wire for valueType.
   */
  int getValueTypeValue();
  /**
   * <code>.FieldValueType value_type = 4;</code>
   * @return The valueType.
   */
  org.apache.airavata.datacatalog.api.FieldValueType getValueType();
}
