// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface MetadataSchemaListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetadataSchemaListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MetadataSchema metadata_schemas = 1;</code>
   */
  java.util.List<org.apache.airavata.datacatalog.api.MetadataSchema> 
      getMetadataSchemasList();
  /**
   * <code>repeated .MetadataSchema metadata_schemas = 1;</code>
   */
  org.apache.airavata.datacatalog.api.MetadataSchema getMetadataSchemas(int index);
  /**
   * <code>repeated .MetadataSchema metadata_schemas = 1;</code>
   */
  int getMetadataSchemasCount();
  /**
   * <code>repeated .MetadataSchema metadata_schemas = 1;</code>
   */
  java.util.List<? extends org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder> 
      getMetadataSchemasOrBuilderList();
  /**
   * <code>repeated .MetadataSchema metadata_schemas = 1;</code>
   */
  org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder getMetadataSchemasOrBuilder(
      int index);
}
