// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

/**
 * Protobuf type {@code MetadataSchemaCreateRequest}
 */
public final class MetadataSchemaCreateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:MetadataSchemaCreateRequest)
    MetadataSchemaCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      MetadataSchemaCreateRequest.class.getName());
  }
  // Use MetadataSchemaCreateRequest.newBuilder() to construct.
  private MetadataSchemaCreateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MetadataSchemaCreateRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_MetadataSchemaCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_MetadataSchemaCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.class, org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.Builder.class);
  }

  private int bitField0_;
  public static final int USER_INFO_FIELD_NUMBER = 1;
  private org.apache.airavata.datacatalog.api.UserInfo userInfo_;
  /**
   * <code>.UserInfo user_info = 1;</code>
   * @return Whether the userInfo field is set.
   */
  @java.lang.Override
  public boolean hasUserInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.UserInfo user_info = 1;</code>
   * @return The userInfo.
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.UserInfo getUserInfo() {
    return userInfo_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : userInfo_;
  }
  /**
   * <code>.UserInfo user_info = 1;</code>
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.UserInfoOrBuilder getUserInfoOrBuilder() {
    return userInfo_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : userInfo_;
  }

  public static final int METADATA_SCHEMA_FIELD_NUMBER = 2;
  private org.apache.airavata.datacatalog.api.MetadataSchema metadataSchema_;
  /**
   * <code>.MetadataSchema metadata_schema = 2;</code>
   * @return Whether the metadataSchema field is set.
   */
  @java.lang.Override
  public boolean hasMetadataSchema() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.MetadataSchema metadata_schema = 2;</code>
   * @return The metadataSchema.
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.MetadataSchema getMetadataSchema() {
    return metadataSchema_ == null ? org.apache.airavata.datacatalog.api.MetadataSchema.getDefaultInstance() : metadataSchema_;
  }
  /**
   * <code>.MetadataSchema metadata_schema = 2;</code>
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder getMetadataSchemaOrBuilder() {
    return metadataSchema_ == null ? org.apache.airavata.datacatalog.api.MetadataSchema.getDefaultInstance() : metadataSchema_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getUserInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getMetadataSchema());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetadataSchema());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest)) {
      return super.equals(obj);
    }
    org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest other = (org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest) obj;

    if (hasUserInfo() != other.hasUserInfo()) return false;
    if (hasUserInfo()) {
      if (!getUserInfo()
          .equals(other.getUserInfo())) return false;
    }
    if (hasMetadataSchema() != other.hasMetadataSchema()) return false;
    if (hasMetadataSchema()) {
      if (!getMetadataSchema()
          .equals(other.getMetadataSchema())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserInfo()) {
      hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    if (hasMetadataSchema()) {
      hash = (37 * hash) + METADATA_SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataSchema().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MetadataSchemaCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MetadataSchemaCreateRequest)
      org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_MetadataSchemaCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_MetadataSchemaCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.class, org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.Builder.class);
    }

    // Construct using org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getUserInfoFieldBuilder();
        getMetadataSchemaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      metadataSchema_ = null;
      if (metadataSchemaBuilder_ != null) {
        metadataSchemaBuilder_.dispose();
        metadataSchemaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_MetadataSchemaCreateRequest_descriptor;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest getDefaultInstanceForType() {
      return org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest build() {
      org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest buildPartial() {
      org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest result = new org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userInfo_ = userInfoBuilder_ == null
            ? userInfo_
            : userInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.metadataSchema_ = metadataSchemaBuilder_ == null
            ? metadataSchema_
            : metadataSchemaBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest) {
        return mergeFrom((org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest other) {
      if (other == org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest.getDefaultInstance()) return this;
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      if (other.hasMetadataSchema()) {
        mergeMetadataSchema(other.getMetadataSchema());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUserInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetadataSchemaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.apache.airavata.datacatalog.api.UserInfo userInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder> userInfoBuilder_;
    /**
     * <code>.UserInfo user_info = 1;</code>
     * @return Whether the userInfo field is set.
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     * @return The userInfo.
     */
    public org.apache.airavata.datacatalog.api.UserInfo getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public Builder setUserInfo(org.apache.airavata.datacatalog.api.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
      } else {
        userInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public Builder setUserInfo(
        org.apache.airavata.datacatalog.api.UserInfo.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public Builder mergeUserInfo(org.apache.airavata.datacatalog.api.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          userInfo_ != null &&
          userInfo_ != org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance()) {
          getUserInfoBuilder().mergeFrom(value);
        } else {
          userInfo_ = value;
        }
      } else {
        userInfoBuilder_.mergeFrom(value);
      }
      if (userInfo_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public Builder clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public org.apache.airavata.datacatalog.api.UserInfo.Builder getUserInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    public org.apache.airavata.datacatalog.api.UserInfoOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            org.apache.airavata.datacatalog.api.UserInfo.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <code>.UserInfo user_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder> 
        getUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.apache.airavata.datacatalog.api.UserInfo, org.apache.airavata.datacatalog.api.UserInfo.Builder, org.apache.airavata.datacatalog.api.UserInfoOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }

    private org.apache.airavata.datacatalog.api.MetadataSchema metadataSchema_;
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.MetadataSchema, org.apache.airavata.datacatalog.api.MetadataSchema.Builder, org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder> metadataSchemaBuilder_;
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     * @return Whether the metadataSchema field is set.
     */
    public boolean hasMetadataSchema() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     * @return The metadataSchema.
     */
    public org.apache.airavata.datacatalog.api.MetadataSchema getMetadataSchema() {
      if (metadataSchemaBuilder_ == null) {
        return metadataSchema_ == null ? org.apache.airavata.datacatalog.api.MetadataSchema.getDefaultInstance() : metadataSchema_;
      } else {
        return metadataSchemaBuilder_.getMessage();
      }
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public Builder setMetadataSchema(org.apache.airavata.datacatalog.api.MetadataSchema value) {
      if (metadataSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadataSchema_ = value;
      } else {
        metadataSchemaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public Builder setMetadataSchema(
        org.apache.airavata.datacatalog.api.MetadataSchema.Builder builderForValue) {
      if (metadataSchemaBuilder_ == null) {
        metadataSchema_ = builderForValue.build();
      } else {
        metadataSchemaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public Builder mergeMetadataSchema(org.apache.airavata.datacatalog.api.MetadataSchema value) {
      if (metadataSchemaBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          metadataSchema_ != null &&
          metadataSchema_ != org.apache.airavata.datacatalog.api.MetadataSchema.getDefaultInstance()) {
          getMetadataSchemaBuilder().mergeFrom(value);
        } else {
          metadataSchema_ = value;
        }
      } else {
        metadataSchemaBuilder_.mergeFrom(value);
      }
      if (metadataSchema_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public Builder clearMetadataSchema() {
      bitField0_ = (bitField0_ & ~0x00000002);
      metadataSchema_ = null;
      if (metadataSchemaBuilder_ != null) {
        metadataSchemaBuilder_.dispose();
        metadataSchemaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public org.apache.airavata.datacatalog.api.MetadataSchema.Builder getMetadataSchemaBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetadataSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    public org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder getMetadataSchemaOrBuilder() {
      if (metadataSchemaBuilder_ != null) {
        return metadataSchemaBuilder_.getMessageOrBuilder();
      } else {
        return metadataSchema_ == null ?
            org.apache.airavata.datacatalog.api.MetadataSchema.getDefaultInstance() : metadataSchema_;
      }
    }
    /**
     * <code>.MetadataSchema metadata_schema = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.MetadataSchema, org.apache.airavata.datacatalog.api.MetadataSchema.Builder, org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder> 
        getMetadataSchemaFieldBuilder() {
      if (metadataSchemaBuilder_ == null) {
        metadataSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.apache.airavata.datacatalog.api.MetadataSchema, org.apache.airavata.datacatalog.api.MetadataSchema.Builder, org.apache.airavata.datacatalog.api.MetadataSchemaOrBuilder>(
                getMetadataSchema(),
                getParentForChildren(),
                isClean());
        metadataSchema_ = null;
      }
      return metadataSchemaBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:MetadataSchemaCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:MetadataSchemaCreateRequest)
  private static final org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest();
  }

  public static org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetadataSchemaCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<MetadataSchemaCreateRequest>() {
    @java.lang.Override
    public MetadataSchemaCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetadataSchemaCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetadataSchemaCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.airavata.datacatalog.api.MetadataSchemaCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

