// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

/**
 * Protobuf enum {@code Permission}
 */
public enum Permission
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OWNER = 0;</code>
   */
  OWNER(0),
  /**
   * <code>READ = 1;</code>
   */
  READ(1),
  /**
   * <code>READ_METADATA = 2;</code>
   */
  READ_METADATA(2),
  /**
   * <code>WRITE = 3;</code>
   */
  WRITE(3),
  /**
   * <code>WRITE_METADATA = 4;</code>
   */
  WRITE_METADATA(4),
  /**
   * <code>MANAGE_SHARING = 5;</code>
   */
  MANAGE_SHARING(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Permission.class.getName());
  }
  /**
   * <code>OWNER = 0;</code>
   */
  public static final int OWNER_VALUE = 0;
  /**
   * <code>READ = 1;</code>
   */
  public static final int READ_VALUE = 1;
  /**
   * <code>READ_METADATA = 2;</code>
   */
  public static final int READ_METADATA_VALUE = 2;
  /**
   * <code>WRITE = 3;</code>
   */
  public static final int WRITE_VALUE = 3;
  /**
   * <code>WRITE_METADATA = 4;</code>
   */
  public static final int WRITE_METADATA_VALUE = 4;
  /**
   * <code>MANAGE_SHARING = 5;</code>
   */
  public static final int MANAGE_SHARING_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Permission valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Permission forNumber(int value) {
    switch (value) {
      case 0: return OWNER;
      case 1: return READ;
      case 2: return READ_METADATA;
      case 3: return WRITE;
      case 4: return WRITE_METADATA;
      case 5: return MANAGE_SHARING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Permission>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Permission> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Permission>() {
          public Permission findValueByNumber(int number) {
            return Permission.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.getDescriptor().getEnumTypes().get(0);
  }

  private static final Permission[] VALUES = values();

  public static Permission valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Permission(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Permission)
}

