// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

public interface RevokePermissionFromGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RevokePermissionFromGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GroupInfo group_info = 1;</code>
   * @return Whether the groupInfo field is set.
   */
  boolean hasGroupInfo();
  /**
   * <code>.GroupInfo group_info = 1;</code>
   * @return The groupInfo.
   */
  org.apache.airavata.datacatalog.api.GroupInfo getGroupInfo();
  /**
   * <code>.GroupInfo group_info = 1;</code>
   */
  org.apache.airavata.datacatalog.api.GroupInfoOrBuilder getGroupInfoOrBuilder();

  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return Whether the dataProduct field is set.
   */
  boolean hasDataProduct();
  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return The dataProduct.
   */
  org.apache.airavata.datacatalog.api.DataProduct getDataProduct();
  /**
   * <code>.DataProduct data_product = 2;</code>
   */
  org.apache.airavata.datacatalog.api.DataProductOrBuilder getDataProductOrBuilder();

  /**
   * <code>.Permission permission = 3;</code>
   * @return The enum numeric value on the wire for permission.
   */
  int getPermissionValue();
  /**
   * <code>.Permission permission = 3;</code>
   * @return The permission.
   */
  org.apache.airavata.datacatalog.api.Permission getPermission();
}
