// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataCatalogAPI.proto
// Protobuf Java Version: 4.28.2

package org.apache.airavata.datacatalog.api;

/**
 * Protobuf type {@code RevokePermissionFromGroupRequest}
 */
public final class RevokePermissionFromGroupRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RevokePermissionFromGroupRequest)
    RevokePermissionFromGroupRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RevokePermissionFromGroupRequest.class.getName());
  }
  // Use RevokePermissionFromGroupRequest.newBuilder() to construct.
  private RevokePermissionFromGroupRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RevokePermissionFromGroupRequest() {
    permission_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_RevokePermissionFromGroupRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_RevokePermissionFromGroupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.class, org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.Builder.class);
  }

  private int bitField0_;
  public static final int GROUP_INFO_FIELD_NUMBER = 1;
  private org.apache.airavata.datacatalog.api.GroupInfo groupInfo_;
  /**
   * <code>.GroupInfo group_info = 1;</code>
   * @return Whether the groupInfo field is set.
   */
  @java.lang.Override
  public boolean hasGroupInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.GroupInfo group_info = 1;</code>
   * @return The groupInfo.
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.GroupInfo getGroupInfo() {
    return groupInfo_ == null ? org.apache.airavata.datacatalog.api.GroupInfo.getDefaultInstance() : groupInfo_;
  }
  /**
   * <code>.GroupInfo group_info = 1;</code>
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.GroupInfoOrBuilder getGroupInfoOrBuilder() {
    return groupInfo_ == null ? org.apache.airavata.datacatalog.api.GroupInfo.getDefaultInstance() : groupInfo_;
  }

  public static final int DATA_PRODUCT_FIELD_NUMBER = 2;
  private org.apache.airavata.datacatalog.api.DataProduct dataProduct_;
  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return Whether the dataProduct field is set.
   */
  @java.lang.Override
  public boolean hasDataProduct() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.DataProduct data_product = 2;</code>
   * @return The dataProduct.
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.DataProduct getDataProduct() {
    return dataProduct_ == null ? org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance() : dataProduct_;
  }
  /**
   * <code>.DataProduct data_product = 2;</code>
   */
  @java.lang.Override
  public org.apache.airavata.datacatalog.api.DataProductOrBuilder getDataProductOrBuilder() {
    return dataProduct_ == null ? org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance() : dataProduct_;
  }

  public static final int PERMISSION_FIELD_NUMBER = 3;
  private int permission_ = 0;
  /**
   * <code>.Permission permission = 3;</code>
   * @return The enum numeric value on the wire for permission.
   */
  @java.lang.Override public int getPermissionValue() {
    return permission_;
  }
  /**
   * <code>.Permission permission = 3;</code>
   * @return The permission.
   */
  @java.lang.Override public org.apache.airavata.datacatalog.api.Permission getPermission() {
    org.apache.airavata.datacatalog.api.Permission result = org.apache.airavata.datacatalog.api.Permission.forNumber(permission_);
    return result == null ? org.apache.airavata.datacatalog.api.Permission.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGroupInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getDataProduct());
    }
    if (permission_ != org.apache.airavata.datacatalog.api.Permission.OWNER.getNumber()) {
      output.writeEnum(3, permission_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGroupInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDataProduct());
    }
    if (permission_ != org.apache.airavata.datacatalog.api.Permission.OWNER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, permission_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest)) {
      return super.equals(obj);
    }
    org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest other = (org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest) obj;

    if (hasGroupInfo() != other.hasGroupInfo()) return false;
    if (hasGroupInfo()) {
      if (!getGroupInfo()
          .equals(other.getGroupInfo())) return false;
    }
    if (hasDataProduct() != other.hasDataProduct()) return false;
    if (hasDataProduct()) {
      if (!getDataProduct()
          .equals(other.getDataProduct())) return false;
    }
    if (permission_ != other.permission_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGroupInfo()) {
      hash = (37 * hash) + GROUP_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getGroupInfo().hashCode();
    }
    if (hasDataProduct()) {
      hash = (37 * hash) + DATA_PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getDataProduct().hashCode();
    }
    hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
    hash = (53 * hash) + permission_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RevokePermissionFromGroupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RevokePermissionFromGroupRequest)
      org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_RevokePermissionFromGroupRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_RevokePermissionFromGroupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.class, org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.Builder.class);
    }

    // Construct using org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getGroupInfoFieldBuilder();
        getDataProductFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      groupInfo_ = null;
      if (groupInfoBuilder_ != null) {
        groupInfoBuilder_.dispose();
        groupInfoBuilder_ = null;
      }
      dataProduct_ = null;
      if (dataProductBuilder_ != null) {
        dataProductBuilder_.dispose();
        dataProductBuilder_ = null;
      }
      permission_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.airavata.datacatalog.api.DataCatalogAPI.internal_static_RevokePermissionFromGroupRequest_descriptor;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest getDefaultInstanceForType() {
      return org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest build() {
      org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest buildPartial() {
      org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest result = new org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.groupInfo_ = groupInfoBuilder_ == null
            ? groupInfo_
            : groupInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dataProduct_ = dataProductBuilder_ == null
            ? dataProduct_
            : dataProductBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.permission_ = permission_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest) {
        return mergeFrom((org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest other) {
      if (other == org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest.getDefaultInstance()) return this;
      if (other.hasGroupInfo()) {
        mergeGroupInfo(other.getGroupInfo());
      }
      if (other.hasDataProduct()) {
        mergeDataProduct(other.getDataProduct());
      }
      if (other.permission_ != 0) {
        setPermissionValue(other.getPermissionValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGroupInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDataProductFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              permission_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.apache.airavata.datacatalog.api.GroupInfo groupInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.GroupInfo, org.apache.airavata.datacatalog.api.GroupInfo.Builder, org.apache.airavata.datacatalog.api.GroupInfoOrBuilder> groupInfoBuilder_;
    /**
     * <code>.GroupInfo group_info = 1;</code>
     * @return Whether the groupInfo field is set.
     */
    public boolean hasGroupInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     * @return The groupInfo.
     */
    public org.apache.airavata.datacatalog.api.GroupInfo getGroupInfo() {
      if (groupInfoBuilder_ == null) {
        return groupInfo_ == null ? org.apache.airavata.datacatalog.api.GroupInfo.getDefaultInstance() : groupInfo_;
      } else {
        return groupInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public Builder setGroupInfo(org.apache.airavata.datacatalog.api.GroupInfo value) {
      if (groupInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupInfo_ = value;
      } else {
        groupInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public Builder setGroupInfo(
        org.apache.airavata.datacatalog.api.GroupInfo.Builder builderForValue) {
      if (groupInfoBuilder_ == null) {
        groupInfo_ = builderForValue.build();
      } else {
        groupInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public Builder mergeGroupInfo(org.apache.airavata.datacatalog.api.GroupInfo value) {
      if (groupInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          groupInfo_ != null &&
          groupInfo_ != org.apache.airavata.datacatalog.api.GroupInfo.getDefaultInstance()) {
          getGroupInfoBuilder().mergeFrom(value);
        } else {
          groupInfo_ = value;
        }
      } else {
        groupInfoBuilder_.mergeFrom(value);
      }
      if (groupInfo_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public Builder clearGroupInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      groupInfo_ = null;
      if (groupInfoBuilder_ != null) {
        groupInfoBuilder_.dispose();
        groupInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public org.apache.airavata.datacatalog.api.GroupInfo.Builder getGroupInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGroupInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    public org.apache.airavata.datacatalog.api.GroupInfoOrBuilder getGroupInfoOrBuilder() {
      if (groupInfoBuilder_ != null) {
        return groupInfoBuilder_.getMessageOrBuilder();
      } else {
        return groupInfo_ == null ?
            org.apache.airavata.datacatalog.api.GroupInfo.getDefaultInstance() : groupInfo_;
      }
    }
    /**
     * <code>.GroupInfo group_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.GroupInfo, org.apache.airavata.datacatalog.api.GroupInfo.Builder, org.apache.airavata.datacatalog.api.GroupInfoOrBuilder> 
        getGroupInfoFieldBuilder() {
      if (groupInfoBuilder_ == null) {
        groupInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.apache.airavata.datacatalog.api.GroupInfo, org.apache.airavata.datacatalog.api.GroupInfo.Builder, org.apache.airavata.datacatalog.api.GroupInfoOrBuilder>(
                getGroupInfo(),
                getParentForChildren(),
                isClean());
        groupInfo_ = null;
      }
      return groupInfoBuilder_;
    }

    private org.apache.airavata.datacatalog.api.DataProduct dataProduct_;
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.DataProduct, org.apache.airavata.datacatalog.api.DataProduct.Builder, org.apache.airavata.datacatalog.api.DataProductOrBuilder> dataProductBuilder_;
    /**
     * <code>.DataProduct data_product = 2;</code>
     * @return Whether the dataProduct field is set.
     */
    public boolean hasDataProduct() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     * @return The dataProduct.
     */
    public org.apache.airavata.datacatalog.api.DataProduct getDataProduct() {
      if (dataProductBuilder_ == null) {
        return dataProduct_ == null ? org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance() : dataProduct_;
      } else {
        return dataProductBuilder_.getMessage();
      }
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public Builder setDataProduct(org.apache.airavata.datacatalog.api.DataProduct value) {
      if (dataProductBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataProduct_ = value;
      } else {
        dataProductBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public Builder setDataProduct(
        org.apache.airavata.datacatalog.api.DataProduct.Builder builderForValue) {
      if (dataProductBuilder_ == null) {
        dataProduct_ = builderForValue.build();
      } else {
        dataProductBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public Builder mergeDataProduct(org.apache.airavata.datacatalog.api.DataProduct value) {
      if (dataProductBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          dataProduct_ != null &&
          dataProduct_ != org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance()) {
          getDataProductBuilder().mergeFrom(value);
        } else {
          dataProduct_ = value;
        }
      } else {
        dataProductBuilder_.mergeFrom(value);
      }
      if (dataProduct_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public Builder clearDataProduct() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dataProduct_ = null;
      if (dataProductBuilder_ != null) {
        dataProductBuilder_.dispose();
        dataProductBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public org.apache.airavata.datacatalog.api.DataProduct.Builder getDataProductBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDataProductFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    public org.apache.airavata.datacatalog.api.DataProductOrBuilder getDataProductOrBuilder() {
      if (dataProductBuilder_ != null) {
        return dataProductBuilder_.getMessageOrBuilder();
      } else {
        return dataProduct_ == null ?
            org.apache.airavata.datacatalog.api.DataProduct.getDefaultInstance() : dataProduct_;
      }
    }
    /**
     * <code>.DataProduct data_product = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.apache.airavata.datacatalog.api.DataProduct, org.apache.airavata.datacatalog.api.DataProduct.Builder, org.apache.airavata.datacatalog.api.DataProductOrBuilder> 
        getDataProductFieldBuilder() {
      if (dataProductBuilder_ == null) {
        dataProductBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.apache.airavata.datacatalog.api.DataProduct, org.apache.airavata.datacatalog.api.DataProduct.Builder, org.apache.airavata.datacatalog.api.DataProductOrBuilder>(
                getDataProduct(),
                getParentForChildren(),
                isClean());
        dataProduct_ = null;
      }
      return dataProductBuilder_;
    }

    private int permission_ = 0;
    /**
     * <code>.Permission permission = 3;</code>
     * @return The enum numeric value on the wire for permission.
     */
    @java.lang.Override public int getPermissionValue() {
      return permission_;
    }
    /**
     * <code>.Permission permission = 3;</code>
     * @param value The enum numeric value on the wire for permission to set.
     * @return This builder for chaining.
     */
    public Builder setPermissionValue(int value) {
      permission_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Permission permission = 3;</code>
     * @return The permission.
     */
    @java.lang.Override
    public org.apache.airavata.datacatalog.api.Permission getPermission() {
      org.apache.airavata.datacatalog.api.Permission result = org.apache.airavata.datacatalog.api.Permission.forNumber(permission_);
      return result == null ? org.apache.airavata.datacatalog.api.Permission.UNRECOGNIZED : result;
    }
    /**
     * <code>.Permission permission = 3;</code>
     * @param value The permission to set.
     * @return This builder for chaining.
     */
    public Builder setPermission(org.apache.airavata.datacatalog.api.Permission value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      permission_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Permission permission = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPermission() {
      bitField0_ = (bitField0_ & ~0x00000004);
      permission_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RevokePermissionFromGroupRequest)
  }

  // @@protoc_insertion_point(class_scope:RevokePermissionFromGroupRequest)
  private static final org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest();
  }

  public static org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RevokePermissionFromGroupRequest>
      PARSER = new com.google.protobuf.AbstractParser<RevokePermissionFromGroupRequest>() {
    @java.lang.Override
    public RevokePermissionFromGroupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RevokePermissionFromGroupRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RevokePermissionFromGroupRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.airavata.datacatalog.api.RevokePermissionFromGroupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

